let emplooyees = [{ "id": 1, "name": "Wrennie", "email": "wpottery0@tuttocitta.it", "gender": "Female" },
{ "id": 2, "name": "Holly-anne", "email": "hangelo1@whitehouse.gov", "gender": "Female" },
{ "id": 3, "name": "Annnora", "email": "aseargeant2@wordpress.com", "gender": "Non-binary" },
{ "id": 4, "name": "Easter", "email": "elanaway3@amazon.com", "gender": "Female" },
{ "id": 5, "name": "Jo-ann", "email": "jfranek4@hugedomains.com", "gender": "Female" },
{ "id": 6, "name": "Dwayne", "email": "dgreenly5@japanpost.jp", "gender": "Male" },
{ "id": 7, "name": "Julienne", "email": "jfransseni6@taobao.com", "gender": "Female" },
{ "id": 8, "name": "Blane", "email": "bgerhold7@twitpic.com", "gender": "Agender" },
{ "id": 9, "name": "Hilda", "email": "hpetrushkevich8@squarespace.com", "gender": "Female" },
{ "id": 10, "name": "Charmion", "email": "cwellstood9@japanpost.jp", "gender": "Female" },
{ "id": 11, "name": "Lynnette", "email": "lborita@nba.com", "gender": "Female" },
{ "id": 12, "name": "Adler", "email": "abourcqb@sciencedirect.com", "gender": "Male" },
{ "id": 13, "name": "Lonnard", "email": "lheildsc@aboutads.info", "gender": "Male" },
{ "id": 14, "name": "Ely", "email": "ebursnalld@flickr.com", "gender": "Male" },
{ "id": 15, "name": "Amalia", "email": "alauriee@rambler.ru", "gender": "Female" },
{ "id": 16, "name": "Grenville", "email": "gsywellf@princeton.edu", "gender": "Agender" },
{ "id": 17, "name": "Eddy", "email": "ehathwayg@ox.ac.uk", "gender": "Female" },
{ "id": 18, "name": "Rourke", "email": "rtowheyh@dailymail.co.uk", "gender": "Genderfluid" },
{ "id": 19, "name": "Fidela", "email": "flarrati@toplist.cz", "gender": "Female" },
{ "id": 20, "name": "Nicolais", "email": "nhaversumj@tmall.com", "gender": "Male" },
{ "id": 21, "name": "Arv", "email": "aivattsk@rakuten.co.jp", "gender": "Male" },
{ "id": 22, "name": "Dominic", "email": "dbusenl@foxnews.com", "gender": "Male" },
{ "id": 23, "name": "Randi", "email": "rmccaddenm@toplist.cz", "gender": "Female" },
{ "id": 24, "name": "Devondra", "email": "dbernardezn@netvibes.com", "gender": "Female" },
{ "id": 25, "name": "Colet", "email": "coldallo@prnewswire.com", "gender": "Male" },
{ "id": 26, "name": "Lock", "email": "ljeffcoatep@instagram.com", "gender": "Male" },
{ "id": 27, "name": "Boycie", "email": "basaafq@mashable.com", "gender": "Male" },
{ "id": 28, "name": "Berk", "email": "brodmanr@pen.io", "gender": "Male" },
{ "id": 29, "name": "Claudian", "email": "ctoons@people.com.cn", "gender": "Male" },
{ "id": 30, "name": "Dyann", "email": "dbeekmant@buzzfeed.com", "gender": "Female" },
{ "id": 31, "name": "Lavena", "email": "llewseyu@comcast.net", "gender": "Female" },
{ "id": 32, "name": "Tresa", "email": "thinkinsv@deliciousdays.com", "gender": "Female" },
{ "id": 33, "name": "Iggy", "email": "iketcherw@pbs.org", "gender": "Male" },
{ "id": 34, "name": "Tomasina", "email": "tdutteridgex@tinyurl.com", "gender": "Female" },
{ "id": 35, "name": "Arline", "email": "alangfitty@quantcast.com", "gender": "Female" },
{ "id": 36, "name": "Elga", "email": "earmalz@cmu.edu", "gender": "Bigender" },
{ "id": 37, "name": "Douglass", "email": "dduiged10@telegraph.co.uk", "gender": "Male" },
{ "id": 38, "name": "Gwenneth", "email": "gneylon11@theatlantic.com", "gender": "Female" },
{ "id": 39, "name": "Gradeigh", "email": "gmears12@umich.edu", "gender": "Male" },
{ "id": 40, "name": "Ardeen", "email": "atarborn13@mapy.cz", "gender": "Female" },
{ "id": 41, "name": "Tomlin", "email": "tdanit14@desdev.cn", "gender": "Male" },
{ "id": 42, "name": "Jillene", "email": "jrogeron15@flickr.com", "gender": "Female" },
{ "id": 43, "name": "Berton", "email": "bbarense16@phpbb.com", "gender": "Male" },
{ "id": 44, "name": "Isidoro", "email": "iwhyatt17@skype.com", "gender": "Male" },
{ "id": 45, "name": "Wolf", "email": "wbiddles18@tinyurl.com", "gender": "Male" },
{ "id": 46, "name": "Aldric", "email": "ajaggs19@chicagotribune.com", "gender": "Male" },
{ "id": 47, "name": "Verine", "email": "vgidman1a@blinklist.com", "gender": "Female" },
{ "id": 48, "name": "Nadine", "email": "norrick1b@bizjournals.com", "gender": "Female" },
{ "id": 49, "name": "Sarette", "email": "sduckworth1c@apple.com", "gender": "Female" },
{ "id": 50, "name": "Anderson", "email": "apullan1d@google.it", "gender": "Male" },
{ "id": 51, "name": "Alexia", "email": "afinney1e@github.io", "gender": "Female" },
{ "id": 52, "name": "Oliver", "email": "omcaloren1f@slideshare.net", "gender": "Agender" },
{ "id": 53, "name": "Claretta", "email": "cmcmenamie1g@sphinn.com", "gender": "Female" },
{ "id": 54, "name": "Chloette", "email": "cthurston1h@list-manage.com", "gender": "Female" },
{ "id": 55, "name": "Lanae", "email": "lcorneil1i@bloomberg.com", "gender": "Female" },
{ "id": 56, "name": "Dannel", "email": "dsodo1j@fc2.com", "gender": "Male" },
{ "id": 57, "name": "Amalie", "email": "aheck1k@t.co", "gender": "Genderfluid" },
{ "id": 58, "name": "Ann", "email": "areboul1l@loc.gov", "gender": "Female" },
{ "id": 59, "name": "Nertie", "email": "ndecleyne1m@linkedin.com", "gender": "Female" },
{ "id": 60, "name": "Maximilianus", "email": "mborlease1n@omniture.com", "gender": "Male" },
{ "id": 61, "name": "Alfy", "email": "acruxton1o@paginegialle.it", "gender": "Female" },
{ "id": 62, "name": "Odette", "email": "oscollick1p@usa.gov", "gender": "Female" },
{ "id": 63, "name": "Piggy", "email": "pandrysiak1q@comcast.net", "gender": "Male" },
{ "id": 64, "name": "Tara", "email": "tletch1r@aboutads.info", "gender": "Female" },
{ "id": 65, "name": "Parker", "email": "pdreelan1s@csmonitor.com", "gender": "Male" },
{ "id": 66, "name": "Clem", "email": "crider1t@abc.net.au", "gender": "Male" },
{ "id": 67, "name": "Zena", "email": "zlegen1u@about.com", "gender": "Genderfluid" },
{ "id": 68, "name": "Napoleon", "email": "ncarratt1v@a8.net", "gender": "Male" },
{ "id": 69, "name": "Alvan", "email": "aarmall1w@mlb.com", "gender": "Male" },
{ "id": 70, "name": "Mariette", "email": "mbrayn1x@who.int", "gender": "Agender" },
{ "id": 71, "name": "Larina", "email": "lurian1y@webmd.com", "gender": "Female" },
{ "id": 72, "name": "Giacobo", "email": "ghampshaw1z@so-net.ne.jp", "gender": "Male" },
{ "id": 73, "name": "Currie", "email": "cpether20@smugmug.com", "gender": "Male" },
{ "id": 74, "name": "Deedee", "email": "dabramov21@marriott.com", "gender": "Female" },
{ "id": 75, "name": "Stacy", "email": "schaudhry22@github.io", "gender": "Male" },
{ "id": 76, "name": "Arny", "email": "avalsler23@wordpress.org", "gender": "Male" },
{ "id": 77, "name": "Jacquenette", "email": "jdavenhall24@icq.com", "gender": "Female" },
{ "id": 78, "name": "Addy", "email": "apindred25@dedecms.com", "gender": "Female" },
{ "id": 79, "name": "Galina", "email": "glindeboom26@sakura.ne.jp", "gender": "Female" },
{ "id": 80, "name": "Augie", "email": "awisbey27@cafepress.com", "gender": "Male" },
{ "id": 81, "name": "Thomasina", "email": "tflanigan28@reuters.com", "gender": "Female" },
{ "id": 82, "name": "Bil", "email": "bjorioz29@1688.com", "gender": "Male" },
{ "id": 83, "name": "Harman", "email": "hstolte2a@topsy.com", "gender": "Male" },
{ "id": 84, "name": "Jada", "email": "jedgeon2b@barnesandnoble.com", "gender": "Female" },
{ "id": 85, "name": "Waldemar", "email": "wklyner2c@purevolume.com", "gender": "Male" },
{ "id": 86, "name": "Shawn", "email": "smarzelo2d@deviantart.com", "gender": "Female" },
{ "id": 87, "name": "Gal", "email": "gderry2e@topsy.com", "gender": "Male" },
{ "id": 88, "name": "Thor", "email": "tschneidau2f@soundcloud.com", "gender": "Male" },
{ "id": 89, "name": "Melodee", "email": "mcregin2g@e-recht24.de", "gender": "Female" },
{ "id": 90, "name": "Alistair", "email": "akleinmintz2h@wikimedia.org", "gender": "Male" },
{ "id": 91, "name": "Gwenore", "email": "ghortop2i@alexa.com", "gender": "Female" },
{ "id": 92, "name": "Cletis", "email": "cvesty2j@apple.com", "gender": "Male" },
{ "id": 93, "name": "Arthur", "email": "ahatwell2k@nba.com", "gender": "Male" },
{ "id": 94, "name": "Bobby", "email": "bwallworth2l@blogtalkradio.com", "gender": "Male" },
{ "id": 95, "name": "Waite", "email": "wdamrell2m@feedburner.com", "gender": "Male" },
{ "id": 96, "name": "Gerda", "email": "gsuggett2n@biblegateway.com", "gender": "Female" },
{ "id": 97, "name": "Henrik", "email": "hcarillo2o@slate.com", "gender": "Male" },
{ "id": 98, "name": "Wade", "email": "wfritter2p@wufoo.com", "gender": "Male" },
{ "id": 99, "name": "Claire", "email": "cbabb2q@cdc.gov", "gender": "Male" },
{ "id": 100, "name": "Dolf", "email": "dblaksley2r@si.edu", "gender": "Male" }]

function display_Data() {
    let rows = "";
    for (let i = 0; i <= emplooyees.length - 1; i++) {
        rows = rows + `<tr>
                        <td>${emplooyees[i].id}</td>
                        <td>${emplooyees[i].name}</td>
                        <td>${emplooyees[i].email}</td>
                        <td>${emplooyees[i].gender.substring(0, 1)}</td>
                        <td>${emplooyees[i].email.split("@").pop()}</td>
                        

                    </tr>`
    }
    document.getElementById('tbody_Data').innerHTML = rows
}